back/models.py
from datetime import datetime

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(256))
    is_delete = db.Column(db.Boolean,default=0)
    create_time=db.Column(db.DateTime,default=datetime.now())
    __tablename__ = 'user'

    def save(self):
        db.session.add(self)
        db.session.commit()



class ArticleType(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    t_name = db.Column(db.String(100), unique=True)
    arts = db.relationship('Article',backref='tp')

    __tablename__='art_type'
class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(100), unique=True,nullable=False)
    desc = db.Column(db.String(100), nullable=False)
    content=db.Column(db.Text, nullable=False)
    create_time=db.Column(db.DateTime,default=datetime.now())
    type=db.Column(db.Integer,db.ForeignKey('art_type.id'))

back/views.py

from flask import Blueprint, request, render_template,redirect, url_for, session

from werkzeug.security import check_password_hash, generate_password_hash

from back.models import db, User, ArticleType, Article
from utils.functions import is_login

back_blueprint = Blueprint('back', __name__)


@back_blueprint.route('/create_db/', methods=['GET'])
def create_db():
    db.create_all()
    return '创建表成功'

@back_blueprint.route('/index/',methods=['GET','POST'])
@is_login
def index():
    user = User.query.filter(User.id == session['user_id'] ).first()
    user1=User.query.all()
    user_count=len(user1)
    return render_template('back/index.html' ,user=user,user_count=user_count)


@back_blueprint.route('/register/',methods=['GET','POST'])
def register():
    if request.method=='GET':
        return render_template('back/register.html')
    if request.method=='POST':
        username=request.form.get('username')
        password = request.form.get('password')
        password2= request.form.get('password2')

        if username and password and password2:
            user=User.query.filter(User.username==username).first()
            if user:
                error='该账号已注册'
                return render_template('back/register.html')
            else:
                if password2==password:
                    user=User()
                    user.username=username
                    user.password=generate_password_hash(password)
                    user.save()
                    return redirect(url_for('back.login'))
                else:
                    error='密码不一致'
                    return render_template('back/register.html', error=error)
        else:
            error='写完整信息'
            return render_template('back/register.html',error=error)
@back_blueprint.route('/logout/',methods=['GET','POST'])
def logout():
    del session['user_id']

    return redirect(url_for('back.login'))

@back_blueprint.route('/login/',methods=['GET','POST'])
def login():
    if request.method=='GET':
        return render_template('back/login.html')
    if request.method=='POST':
        username=request.form.get('username')
        password = request.form.get('password')

        if username and password:
            user=User.query.filter(User.username==username).first()
            if not user:

                error='该账号不存在'
                return render_template('back/login.html')
            if not check_password_hash(user.password,password):
                error=',账号,密码错误'
                return render_template('back/login.html',error=error)
            session['user_id']=user.id
            return redirect(url_for('back.index'))
        else:
            error='请写完整信息'
            return render_template('back/login.html', error=error)

@back_blueprint.route('/a_type/',methods=['GET','POST'])
def a_type():
    if request.method=='GET':
        types=ArticleType.query.all()
        count_types = len(types)
        user = User.query.filter(User.id == session['user_id']).first()
        return render_template('back/category_list.html', types=types,user=user,count_types=count_types)
@back_blueprint.route('/add_type/',methods=['GET','POST'])
def add_type():
    if request.method=='GET':
        user = User.query.filter(User.id == session['user_id']).first()
        return render_template('back/category_add.html',user=user)
    if request.method=='POST':
        atype=request.form.get('atype')
        if atype:
            art_type=ArticleType()
            art_type.t_name=atype
            db.session.add(art_type)
            db.session.commit()
            return redirect(url_for('back.a_type'))
            # return render_template('back/category_list.html',user=user)
        else:
            error='请写分类信息'
            return render_template('back/category_add.html', error=error)


@back_blueprint.route('/del_type/<int:id>/',methods=['GET','POST'])
def del_type(id):

    atype=ArticleType.query.get(id)
    db.session.delete(atype)
    db.session.commit()
    return redirect(url_for('back.a_type'))


@back_blueprint.route('/article_list/',methods=['GET'])
def article_list():
    user = User.query.filter(User.id == session['user_id']).first()
    articles=Article.query.all()
    aritcle_count=len(articles)
    return render_template('back/article_list.html',articles=articles,user=user,aritcle_count=aritcle_count)
@back_blueprint.route('/article_add/',methods=['GET','POST'])
def article_add():
    if request.method=='GET':
        user = User.query.filter(User.id == session['user_id']).first()
        types=ArticleType.query.all()
        return render_template('back/article_detail.html', types=types,user=user)
    if request.method=='POST':

        title=request.form.get('title')
        desc = request.form.get('desc')
        category = request.form.get('category')
        content = request.form.get('content')
        if title and desc and category and content:
            art=Article()
            art.title=title
            art.desc=desc
            art.content=content
            art.type=category
            db.session.add(art)
            db.session.commit()
            return redirect(url_for('back.article_list'))
        else:
            error='请写完整的文章信息'
            return render_template('back/article_detail.html', error=error)
@back_blueprint.route('/del_article/<int:id>/',methods=['GET','POST'])
def del_article(id):
    atype=Article.query.get(id)
    db.session.delete(atype)
    db.session.commit()
    return redirect(url_for('back.article_list'))

web/views.py

from flask import Blueprint, request, render_template,\
    redirect, url_for
from back.models import Article


web_blueprint = Blueprint('web', __name__)

@web_blueprint.route('/index/',methods=['GET','POST'])
def index():
    articles=Article.query.limit(14).all()

    return render_template('web/index.html',articles=articles)


@web_blueprint.route('/info/<int:id>/',methods=['GET','POST'])
def info(id):
    article=Article.query.get(id)
    return render_template('web/info.html',article=article)
























































# @web_blueprint.route('/about/',methods=['GET','POST'])
# def about():
#     return render_template('web/about.html')
#
# @web_blueprint.route('/gbook/',methods=['GET','POST'])
# def gbook():
#     return render_template('web/gbook.html')
#
#
#
# @web_blueprint.route('/infopic/',methods=['GET','POST'])
# def infopic():
#     return render_template('web/infopic.html')
#
# @web_blueprint.route('/list/',methods=['GET','POST'])
# def list():
#     return render_template('web/list.html')
#
# @web_blueprint.route('/share/',methods=['GET','POST'])
# def share():
#     return render_template('web/share.html')

templates/back/article_detail.html
{% extends 'back/base_main.html' %}

 {% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <div class="row">
       <h5><li><a href="{{ url_for("back.article_list") }}">返回文章</a></li></h5>
      <form action="" method="post" >
        {{ error }}
          <div class="col-md-9">
            <h1 class="page-header">文章标题</h1>
            <div class="form-group">
              <input type="text" id="article-title" name="title" class="form-control" >
            </div>

            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>文章描述</span></h2>
              <div class="add-article-box-content">
              	<input type="text" class="form-control"  name="desc">
              </div>
            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>分类</span></h2>
             <div class="add-article-box-content">
                <select class="select" name="category">
                    {% for type in types %}
                    <option value="{{ type.id }}">{{ type.t_name }}</option>
                    {% endfor %}
                </select>
             </div>
                <div class="add-article-box">
              <h2 class="add-article-box-title"><span>文章详情</span></h2>
              <div class="add-article-box-content">
              <input type="text" class="form-control"  name="content">
              </div>
            </div>
          </div>
                <button class="btn btn-primary" type="submit">提交</button>
              </div>
        </form>
      </div>
    </div>
{% endblock %}
{% block js2 %}
<script src="/static/back/js/bootstrap.min.js"></script>
<script src="/static/back/js/admin-scripts.js"></script>
<script src="/static/back/lib/ueditor/ueditor.config.js"></script>
<script src="/static/back/lib/ueditor/ueditor.all.min.js"> </script>
<script src="/static/back/lib/ueditor/lang/zh-cn/zh-cn.js"></script>
{% endblock %}

<script >
{#<script type="text/javascript">#}
var editor = UE.getEditor('article-content');
window.onresize=function(){
    window.location.reload();
}
var _uploadEditor;
$(function () {
    //重新实例化一个编辑器，防止在上面的editor编辑器中显示上传的图片或者文件
    _uploadEditor = UE.getEditor('uploadEditor');
    _uploadEditor.ready(function () {
        //设置编辑器不可用
        //_uploadEditor.setDisabled();
        //隐藏编辑器，因为不会用到这个编辑器实例，所以要隐藏
        _uploadEditor.hide();
        //侦听图片上传
        _uploadEditor.addListener('beforeInsertImage', function (t, arg) {
            //将地址赋值给相应的input,只去第一张图片的路径
            $("#pictureUpload").attr("value", arg[0].src);
            //图片预览
            //$("#imgPreview").attr("src", arg[0].src);
        })
        //侦听文件上传，取上传文件列表中第一个上传的文件的路径
        _uploadEditor.addListener('afterUpfile', function (t, arg) {
            $("#fileUpload").attr("value", _uploadEditor.options.filePath + arg[0].url);
        })
    });
});
//弹出图片上传的对话框
$('#upImage').click(function () {
    var myImage = _uploadEditor.getDialog("insertimage");
    myImage.open();
});
//弹出文件上传的对话框
function upFiles() {
    var myFiles = _uploadEditor.getDialog("attachment");
    myFiles.open();
}
</script>

templates/back/article_list.html
{% extends 'back/base_main.html' %}


 {% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">


      <form action="" method="post" >
        <ol class="breadcrumb">
            <h1>文章列表</h1>
          <li><a href="{{ url_for("back.article_add") }}">增加文章</a></li>
        </ol>
        <h1 class="page-header">管理 <span class="badge">{{ aritcle_count }}</span></h1>
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th><span class="glyphicon glyphicon-th-large"></span> <span class="visible-lg">文章标题</span></th>
                <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">文章分类</span></th>
                <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">日期</span></th>
                <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
              </tr>
            </thead>
            <tbody>

            {% for article in articles %}

              <tr>
                  <td class="article-title">{{ article.title }}</td>
                  <td class="article-title">{{ article.tp.t_name }}</td>
                  <td class="article-title">{{ article.create_time }}</td>
                <td><a href="{{ url_for("back.del_article",id=article.id) }}">删除</a> <a rel="6"></a></td>
              </tr>

            {% endfor %}
            </tbody>
          </table>
        </div>
        <footer class="message_footer">
          <nav>
            <div class="btn-toolbar operation" role="toolbar">
              <div class="btn-group" role="group"> <a class="btn btn-default" onClick="select()">全选</a> <a class="btn btn-default" onClick="reverse()">反选</a> <a class="btn btn-default" onClick="noselect()">不选</a> </div>
              <div class="btn-group" role="group">
                <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="删除全部选中" name="checkbox_delete">删除</button>
              </div>
            </div>
            <ul class="pagination pagenav">
              <li class="disabled"><a aria-label="Previous"> <span aria-hidden="true">&laquo;</span> </a> </li>
              <li class="active"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#" aria-label="Next"> <span aria-hidden="true">&raquo;</span> </a> </li>
            </ul>
          </nav>
        </footer>
      </form>



    </div>


{% endblock %}
{% block js2 %}
<script src="/static/back/js/bootstrap.min.js"></script>
<script src="/static/back/js/admin-scripts.js"></script>
{% endblock %}
<script>
//是否确认删除
$(function(){   
	$("#main table tbody tr td a").click(function(){
		var name = $(this);
		var id = name.attr("rel"); //对应id  
		if (event.srcElement.outerText == "删除") 
		{
			if(window.confirm("此操作不可逆，是否确认？"))
			{
				$.ajax({
					type: "POST",
					url: "/Article/delete",
					data: "id=" + id,
					cache: false, //不缓存此页面   
					success: function (data) {
						window.location.reload();
					}
				});
			};
		};
	});   
});
</script>


templates/back/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}
    {% block js1 %}
    {% endblock %}
</head>
<body>
<section class="container-fluid">
    {% block header %}
    {% endblock %}
    <div class="row">
        {% block aside %}
        {% endblock %}

        {% block content %}
        {% endblock %}
    </div>
</section>
{% block dialog %}
{% endblock %}
{% block js2 %}
{% endblock %}
</body>
</html>

templates/back/base_main.html
{% extends 'back/base.html' %}


{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/back/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/back/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/back/css/font-awesome.min.css">
<link rel="apple-touch-icon-precomposed" href="/static/back/images/icon/icon.png">
<link rel="shortcut icon" href="/static/back/images/icon/favicon.ico">
{% endblock %}
{% block js1 %}
    <script src="/static/back/js/jquery-2.1.4.min.js"></script>
{% endblock %}


{% block header %}
    <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">YlsatCMS</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">

            <li><a href="">用户名 <span class="badge"></span>{{ user.username }}</a></li>
            <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>
                <li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>
              </ul>
            </li>
            <li><a href="{{ url_for("back.logout") }}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a data-toggle="modal" data-target="#WeChat"></a></li>
          </ul>
          <form action="" method="post" class="navbar-form navbar-right" role="search">
            <div class="input-group">
              <input type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
              <span class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
    </nav>
  </header>
{% endblock %}

 {% block aside %}
     <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li><a href="{{ url_for("back.index") }}">报告</a></li>
      </ul>
      <ul class="nav nav-sidebar">

        <li><a href="{{ url_for("back.a_type") }}">文章分类</a></li>
        <li><a href="{{ url_for("back.article_list") }}">文章列表</a></li>
        <li><a data-toggle="tooltip" data-placement="top" title="网站暂无留言功能">留言</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="">栏目</a></li>
        <li><a class="dropdown-toggle" id="otherMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">其他</a>
          <ul class="dropdown-menu" aria-labelledby="otherMenu">
            <li><a href="">友情链接</a></li>
            <li><a href="">访问记录</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a class="dropdown-toggle" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">用户</a>
          <ul class="dropdown-menu" aria-labelledby="userMenu">
            <li><a href="#">管理用户组</a></li>
            <li><a href="">管理用户</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="">管理登录日志</a></li>
          </ul>
        </li>
        <li><a class="dropdown-toggle" id="settingMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">设置</a>
          <ul class="dropdown-menu" aria-labelledby="settingMenu">
            <li><a href="">基本设置</a></li>
            <li><a href="">用户设置</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">安全配置</a></li>
            <li role="separator" class="divider"></li>
            <li class="disabled"><a>扩展菜单</a></li>
          </ul>
        </li>
      </ul>
    </aside>
 {% endblock %}


templates/back/category_add.html

{% extends 'back/base_main.html' %}

 {% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <h1 class="page-header">文章分类</h1>
        <a href="{{ url_for("back.a_type") }}" class="icon">返回文章分类列表</a>

      <form action="" method="post">
          <ul>
              <li>
                  <label for="category-name">分类名称</label>

                  <input type="text" name="atype"><button class="btn btn-primary" type="submit">提交</button>
              </li>
          </ul>

      </form>

    </div>
{% endblock %}
{% block js2 %}
<script src="/static/back/js/bootstrap.min.js"></script>
<script src="/static/back/js/admin-scripts.js"></script>
{% endblock %}


templates/back/category_list.html
{% extends 'back/base_main.html' %}


 {% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
        <div class="col-md-7">
          <h1 class="page-header">分类列表 <span class="badge">{{ count_types }}</span></h1>
            <a href="{{ url_for("back.add_type") }}" class="icon">添加文章分类</a>
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th><span class="glyphicon glyphicon-paperclip"></span> <span class="visible-lg">分类名</span></th>
                  <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">操作</span></th>
                </tr>
              </thead>
              <tbody>

              {% for type in types %}
                <tr>
                  <td>{{ type.t_name }}</td>
                  <td><a href="{{ url_for("back.del_type",id=type.id) }}">删除</a> <a rel="1">修改</a></td>
                </tr>
              {% endfor %}

              </tbody>
            </table>
        </div>
      </div>
    </div>
{% endblock %}
{% block js2 %}
<script src="/static/back/js/bootstrap.min.js"></script>
<script src="/static/back/js/admin-scripts.js"></script>
{% endblock %}
<script>
//是否确认删除
$(function(){   
	$("#main table tbody tr td a").click(function(){
		var name = $(this);
		var id = name.attr("rel"); //对应id  
		if (event.srcElement.outerText === "删除") 
		{
			if(window.confirm("此操作不可逆，是否确认？"))
			{
				$.ajax({
					type: "POST",
					url: "/Category/delete",
					data: "id=" + id,
					cache: false, //不缓存此页面   
					success: function (data) {
						window.location.reload();
					}
				});
			};
		};
	});   
});
</script>


templates/back/login.html
<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>异清轩博客管理系统</title>
<link rel="stylesheet" type="text/css" href="/static/back/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/back/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/back/css/login.css">
<link rel="apple-touch-icon-precomposed" href="/static/back/images/icon/icon.png">
<link rel="shortcut icon" href="/static/back/images/icon/favicon.ico">
<script src="/static/back/js/jquery-2.1.4.min.js"></script>

</head>

<body class="user-select">
<div class="container">
  <div class="siteIcon"><img src="/static/back/images/icon/icon.png" alt="" data-toggle="tooltip" data-placement="top" title="欢迎使用异清轩博客管理系统" draggable="false" /></div>
  <form action="" method="post" autocomplete="off" class="form-signin">
    <h2 class="form-signin-heading">管理员登录</h2>
    <label for="userName" class="sr-only">用户名</label>
    <input type="text" id="userName" name="username" class="form-control" placeholder="请输入用户名" required autofocus autocomplete="off" maxlength="10">
    <label for="userPwd" class="sr-only">密码</label>
    <input type="password" id="userPwd" name="password" class="form-control" placeholder="请输入密码" required autocomplete="off" maxlength="18">
    <a href="login.html"><button class="btn btn-lg btn-primary btn-block" type="submit" id="signinSubmit">登录</button></a>
  </form>
  <div class="footer">
    <p><a href="index.html" data-toggle="tooltip" data-placement="left" title="不知道自己在哪?">回到后台 →</a></p>
  </div>
</div>
<script src="/static/back/js/bootstrap.min.js"></script>
<script>
$('[data-toggle="tooltip"]').tooltip();
window.oncontextmenu = function(){
	//return false;
};
$('.siteIcon img').click(function(){
	window.location.reload();
});
$('#signinSubmit').click(function(){
	if($('#userName').val() === ''){
		$(this).text('用户名不能为空');
	}else if($('#userPwd').val() === ''){
		$(this).text('密码不能为空');
	}else{
		$(this).text('请稍后...');
	}
});
</script>
</body>
</html>

templates/web/index.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/web/css/base.css" rel="stylesheet">
<link href="/static/web/css/index.css" rel="stylesheet">
<link href="/static/web/css/m.css" rel="stylesheet">
<script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/web/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">杨青个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="index.html">网站首页</a></li>
      <li><a href="share.html">我的相册</a></li>
      <li><a href="list.html">我的日记</a></li>
      <li><a href="about.html">关于我</a></li>
      <li><a href="gbook.html">留言</a></li>
      <li><a href="info.html">内容页</a></li>
      <li><a href="infopic.html">内容页</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
      <div class="about_me">
        <h2>关于我</h2>
        <ul>
          <i><img src="/static/web/images/4.jpg"></i>
          <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
        </ul>
      </div>
      <div class="wdxc">
        <h2>我的相册</h2>
        <ul>
          <li><a href="/"><img src="/static/web/images/7.jpg"></a></li>
          <li><a href="/"><img src="/static/web/images/8.jpg"></a></li>
          <li><a href="/"><img src="/static/web/images/9.jpg"></a></li>
          <li><a href="/"><img src="/static/web/images/10.jpg"></a></li>
          <li><a href="/"><img src="/static/web/images/11.jpg"></a></li>
          <li><a href="/"><img src="/static/web/images/12.jpg"></a></li>
        </ul>
      </div>
      <div class="search">
        <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
          <li><a href="/">学无止境（33）</a></li>
          <li><a href="/">日记（19）</a></li>
          <li><a href="/">慢生活（520）</a></li>
          <li><a href="/">美文欣赏（40）</a></li>
        </ul>
      </div>
      <div class="tuijian">
        <h2>站长推荐</h2>
        <ul>
          <li><a href="/">你是什么人便会遇上什么人</a></li>
          <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
          <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
          <li><a href="/">个人博客模板《绅士》后台管理</a></li>
          <li><a href="/">你是什么人便会遇上什么人</a></li>
          <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
          <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
          <li><a href="/">个人博客模板《绅士》后台管理</a></li>
        </ul>
      </div>
      <div class="links">
        <h2>友情链接</h2>
        <ul>
          <a href="http://www.yangqq.com">杨青个人博客</a> <a href="http://www.yangqq.com">杨青博客</a>
        </ul>
      </div>
      <div class="guanzhu">
        <h2>关注我 么么哒</h2>
        <ul>
          <img src="/static/web/images/wx.jpg">
        </ul>
      </div>
  </aside>
  <main class="r_box">
      {% for article in articles %}
      <li>
          <h3><a href="{{ url_for("web.info",id= article.id) }}">{{ article.title }}</a></h3>
          <p>{{ article.desc }}</p>
      </li>
      {% endfor %}

  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>